### ISSUE TITLE
关于 `\memologo` 在` .tex`  文件中输入不正确的问题

### ISSUE THREAD

**Issue by sikouhjw** [latexstudio-org/mcmthesis#1]
`mcmthesis-demo.tex` 的第 `87` 行
```latex
%% \logo{\LARGE I'm pretending to be a LOGO!}
```
取消注释后直接编译会报错：`未定义的控制序列`，查看 `mcmthesis.pdf` 后发现应改成 `\memologo{\LARGE I'm pretending to be a LOGO!}`

**Comment by latexstudio** [comment]
收到了.
