### ISSUE TITLE
页眉页码设置问题

### ISSUE THREAD

**Issue by mybelovedlz** [latexstudio-org/mcmthesis#2]
官方要求目录、附录不计入页数，但在模板中其实计入了。

**Comment by suyoumo** [comment]
所以呢，要不要改，把附录的页数去掉，怎么去掉

**Comment by Naylenv** [comment]
附录页数怎么去掉呢

**Comment by sikouhjw** [comment]
> Your solution report should start with the Summary Sheet followed by the team’s solution. Ensure your solution meets the 25 page limit requirement. A Table of Contents is encouraged and does count toward the page limit. Reference list (or Bibliography), notes pages, and any appendices now count toward the page limit and should be included after the solution pages.

ref: [https://www.comap.com/undergraduate/contests/mcm/instructions.php](https://www.comap.com/undergraduate/contests/mcm/instructions.php)

问题可以 close 了

**Comment by mybelovedlz** [comment]
> > Your solution report should start with the Summary Sheet followed by the team’s solution. Ensure your solution meets the 25 page limit requirement. A Table of Contents is encouraged and does count toward the page limit. Reference list (or Bibliography), notes pages, and any appendices now count toward the page limit and should be included after the solution pages.
> 
> ref: https://www.comap.com/undergraduate/contests/mcm/instructions.php
> 
> 问题可以 close 了

以一种奇怪的方式解决了。。。
